#!/bin/sh

[ "$CLJS_WATCH" ] || CLJS_WATCH=cljs-watch

compiler="$CLOJURESCRIPT_HOME/bin/cljsc"
[ "$1" ] && compiler="$CLJS_WATCH"

rm -r out

exec "$compiler" src '{:output-to "out/all.js" :output-dir "out" :optimizations :simple}'
