#!/bin/sh

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo 'usage: ./run-tests [arg]'
  echo '    Run tests using the javascript interpreter $JS or d8.'
  echo '    If arg is present, compile before testing using'
  echo '    $CLOJURESCRIPT_HOME/bin/cljsc'
  exit 1
fi

[ "$JS" ] || JS=d8

mkdir -p out
if [ "$1" ]; then
  "$CLOJURESCRIPT_HOME/bin/cljsc" cljs \
    '{:output-dir "out" :output-to "out/testall.js" :optimizations :simple}' \
    || exit 1
fi
"$JS" out/testall.js
